### ISSUE TITLE
oc生成cell带t

### ISSUE THREAD

**Issue by medivh-xiong** [SeongBrave/gckit#1]
无论加不加_线都会有个t

**Comment by SeongBrave** [comment]
@medivh-xiong t表示是UITableViewCell c表示UICollectioviewCell,用于区别这两种不同的cell的

**Comment by medivh-xiong** [comment]
那如何能去掉t，现在生成的cell名称都是xxx_tcell，不想要加t




| |
熊欣
|
|
xxshijianjs@163.com
|
签名由网易邮箱大师定制


在2019年03月6日 08:25，SeongBrave<notifications@github.com> 写道：

@medivh-xiong t表示是UITableViewCell c表示UICollectioviewCell,用于区别这两种不同的cell的

**Comment by SeongBrave** [comment]
@medivh-xiong 是可以的，比较麻烦点，不能使用默认的cell模板了。首先你自定义一种文件类型，参考[文件类型配置](https://seongbrave.github.io/gckit/guide/advanced/gtype-config.html)，然后再自定义一个对应的模板就可以了

**Comment by sunlight2728** [comment]
支持 OC  版本吗

**Comment by SeongBrave** [comment]
@sunlight2728  参考[设置用户配置
#](https://seongbrave.github.io/gckit/guide/basic-config.html#%E8%AE%BE%E7%BD%AE%E7%94%A8%E6%88%B7%E9%85%8D%E7%BD%AE)可以配置成Objective-C语言的
