### ISSUE TITLE
自定义模板出现错误

### ISSUE THREAD

**Issue by xx-li** [SeongBrave/gckit#3]
谢谢这个开源项目，能帮助我提高开发效率，但是使用自定义模板时碰到了如下问题：

我在项目中自定义了模板，模板中新增了内容`engine`, 在配置文件中设置如下：
```json
"gTypes": [
    "viewcontroller",
    "viewmodel",
    "model",
    "cell",
    "api",
    "engine"  //新增
  ],
  "engine": {  //新增
    "path": "Engine",
    "suffix": "_engine",
    "isProject": false
  },
```
在模板文件的swift目录下，添加了如下模板：
```
.
├── api
├── cell
├── core
├── engine   //添加的模板
│   ├── all.template
│   ├── common.template
│   ├── inherit.template
│   └── normal.template
├── model
├── router
├── viewcontroller
└── viewmodel
```
但是使用`gckit g product`命令时，报错：
`Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/gckit/gckit-templates/templates/swift/engine/all.template'`
按说明文档，模板的读取顺序是：`项目级别 -> 用户级别 -> Gckit-CLI 默认`，不应该发生此错误。 
我在错误提示的目录下添加同样的engine模板后可以执行命令。但是生成的文件名错了：
```
.
├── Api
│   └── Product_api.swift
├── Engine
│   └── undefined.swift   //文件名生成错误
├── Model
│   └── Product_model.swift
├── View
│   └── tCell
│       └── Product_tCell.swift
├── ViewController
│   └── Product_vc.swift
└── ViewModel
    └── Product_vm.swift
```

文件的内容也出现了错误，其中的`<%= className %>`全部生成的是空字符。

**Comment by SeongBrave** [comment]
模板文件目录放在那呢？是在 .gckit目录下吗？

**Comment by xx-li** [comment]
是的。 放在项目目录的.gckit目录下。

生成后的目录如下：
```
.
├── Api
│   └── Product_api.swift
├── Engine
│   └── undefined.swift   //文件名生成错误
├── Model
│   └── Product_model.swift
├── View
│   └── tCell
│       └── Product_tCell.swift
├── ViewController
│   └── Product_vc.swift
└── ViewModel
    └── Product_vm.swift
```

其它模板修改都是OK的，就只有Engine目录下出现了问题。

**Comment by SeongBrave** [comment]
哦哦，不好意思啊，我完了试下吧，这块确实没有测过

**Comment by SeongBrave** [comment]
@xx-li 您好，那个问题已经解决了，你更新下看下版本为0.0.5

**Comment by xx-li** [comment]
@SeongBrave  Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/gckit/gckit-templates/templates/swift/engine/all.template' 问题修复了，但是生成问题依然存在，配置文件设置如下：
```JSON
"gTypes": [
    "viewcontroller",
    "model",
    "cell",
    "api",
    "engine"
  ],
  "engine": {
    "path": "Engine",
    "suffix": "_engine",
    "isProject": true   //值为true或false结果一样
  }, 
```
`isProject`字段的用途有点费解，不太理解它的含义。

**Comment by SeongBrave** [comment]
@xx-li https://seongbrave.github.io/gckit/config/#gtype-isproject 这块有一个简单的说明，我当时设置这个参数，主要考虑到有些文件是项目级别配置的，比如Appdelegate或者我默认的core、router都是根据项目级别的，名称不是根据你输入的文件名生成而是读取项目名称生成的
